name: Laravel Deploy to Hostinger

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql

      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      # Node Installation & Build
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install NPM Dependencies
        run: npm install

      - name: Build assets with Vite
        run: npm run build

      - name: Prepare Laravel Environment
        run: |
          cp .env.example .env
          php artisan key:generate

      # Project deployment excluding public folder
      - name: Deploy Project to Hostinger (excluding public folder)
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USERNAME }}
          password: ${{ secrets.HOSTINGER_PASSWORD }}
          port: 65002
          source: "."
          target: "/home/u679007062/domains/devstagram.codebybryan.tech"
          rm: true

      # Deploy the contents of the Laravel public folder to the public_html/public_html directory.
      - name: Deploy public folder content to Hostinger
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USERNAME }}
          password: ${{ secrets.HOSTINGER_PASSWORD }}
          port: 65002
          source: "public/*"
          target: "/home/u679007062/domains/devstagram.codebybryan.tech/public_html/"
          strip_components: 1
          rm: true

      - name: Create .env file
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USERNAME }}
          password: ${{ secrets.HOSTINGER_PASSWORD }}
          port: 65002
          script: |
            cat > /home/u679007062/domains/devstagram.codebybryan.tech/.env << EOF
            APP_NAME=Laravel
            APP_ENV=local
            APP_KEY=${{ secrets.APP_KEY }}
            APP_DEBUG=true
            APP_URL=http://localhost

            LOG_CHANNEL=stack
            LOG_DEPRECATIONS_CHANNEL=null
            LOG_LEVEL=debug

            DB_CONNECTION=mysql
            DB_HOST=mysql
            DB_PORT=3306
            DB_DATABASE=${{ secrets.DB_DATABASE }}
            DB_USERNAME=${{ secrets.DB_USERNAME }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}

            BROADCAST_DRIVER=log
            CACHE_DRIVER=file
            FILESYSTEM_DISK=local
            QUEUE_CONNECTION=sync
            SESSION_DRIVER=file
            SESSION_LIFETIME=120

            MEMCACHED_HOST=127.0.0.1

            REDIS_HOST=redis
            REDIS_PASSWORD=null
            REDIS_PORT=6379

            MAIL_MAILER=smtp
            MAIL_HOST=mailpit
            MAIL_PORT=1025
            MAIL_USERNAME=null
            MAIL_PASSWORD=null
            MAIL_ENCRYPTION=null
            MAIL_FROM_ADDRESS="hello@example.com"
            MAIL_FROM_NAME="${APP_NAME}"

            AWS_ACCESS_KEY_ID=
            AWS_SECRET_ACCESS_KEY=
            AWS_DEFAULT_REGION=us-east-1
            AWS_BUCKET=
            AWS_USE_PATH_STYLE_ENDPOINT=false

            PUSHER_APP_ID=
            PUSHER_APP_KEY=
            PUSHER_APP_SECRET=
            PUSHER_HOST=
            PUSHER_PORT=443
            PUSHER_SCHEME=https
            PUSHER_APP_CLUSTER=mt1

            VITE_APP_NAME="${APP_NAME}"
            VITE_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
            VITE_PUSHER_HOST="${PUSHER_HOST}"
            VITE_PUSHER_PORT="${PUSHER_PORT}"
            VITE_PUSHER_SCHEME="${PUSHER_SCHEME}"
            VITE_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"

            SCOUT_DRIVER=meilisearch
            MEILISEARCH_HOST=http://meilisearch:7700

            MEILISEARCH_NO_ANALYTICS=false
            EOF

      - name: Run Post-Deployment Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USERNAME }}
          password: ${{ secrets.HOSTINGER_PASSWORD }}
          port: 65002
          script: |
            cd /home/u679007062/domains/devstagram.codebybryan.tech
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
